schema: './schema.graphql'
documents: 'client/**/*.graphql'
extensions:
  codegen:
    generates:
      client/types/graphql.tsx:
        plugins:
          - 'typescript'
          - 'typescript-operations'
          - 'typescript-react-apollo'
        config:
          reactApolloVersion: 3
          withResultTypes: true
          avoidOptionals: true
        hooks:
          afterOneFileWrite:
            - prettier --write
            - eslint --fix
